sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  - docker build -t wrk .

script:
  - docker run -i wrk -c2 -d1 https://www.google.com | tee result  
  - echo "Validating the test results..."
  - bash -c "[ -s result ]"
